In [ ]:
# PyTorch Tensor Operations Colab Notebook
import torch

In [ ]:
# Basic Tensor Creation
scalar = torch.tensor(5)  # Scalar (Rank-0 Tensor)
vector = torch.tensor([1, 2, 3])  # Vector (Rank-1 Tensor)
matrix = torch.tensor([[1, 2], [3, 4]])  # Matrix (Rank-2 Tensor)
tensor_3d = torch.rand((3, 3, 3))  # Rank-3 Tensor with random values

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("3D Tensor:\n", tensor_3d)

Scalar: tensor(5)
Vector: tensor([1, 2, 3])
Matrix:
 tensor([[1, 2],
        [3, 4]])
3D Tensor:
 tensor([[[0.3339, 0.6557, 0.1369],
         [0.5948, 0.4374, 0.9835],
         [0.1709, 0.4897, 0.9679]],

        [[0.3059, 0.7301, 0.5698],
         [0.0817, 0.7697, 0.8632],
         [0.2584, 0.3274, 0.7625]],

        [[0.8846, 0.5441, 0.3923],
         [0.8557, 0.2905, 0.8216],
         [0.0644, 0.2630, 0.4659]]])


In [ ]:
# Basic Arithmetic Operations
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
add_result = a + b
mul_result = a * b
matmul_result = torch.matmul(a, b)

print("\nAddition:\n", add_result)
print("Element-wise Multiplication:\n", mul_result)
print("Matrix Multiplication:\n", matmul_result)


Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


In [ ]:
# Advanced Operations
reshaped_tensor = a.view(-1)  # Reshaping
transposed_tensor = a.T       # Transposition
reduced_sum = a.sum()         # Summing all elements
broadcasted_tensor = a + torch.tensor([1.0, 2.0])  # Broadcasting

print("\nReshaped Tensor:", reshaped_tensor)
# Advanced Operations
reshaped_tensor = a.view(-1)  # Reshaping
transposed_tensor = a.T       # Transposition
reduced_sum = a.sum()         # Summing all elements
broadcasted_tensor = a + torch.tensor([1.0, 2.0])  # Broadcasting

print("\nReshaped Tensor:", reshaped_tensor)
print("Transposed Tensor:\n", transposed_tensor)
print("Reduced Sum:", reduced_sum.item())
print("Broadcasted Tensor:\n", broadcasted_tensor)


Reshaped Tensor: tensor([1., 2., 3., 4.])

Reshaped Tensor: tensor([1., 2., 3., 4.])
Transposed Tensor:
 tensor([[1., 3.],
        [2., 4.]])
Reduced Sum: 10.0
Broadcasted Tensor:
 tensor([[2., 4.],
        [4., 6.]])


In [ ]:
# Einsum Demonstrations in PyTorch
einsum_matmul = torch.einsum('ij,jk->ik', a, b)    # Matrix Multiplication using einsum
einsum_outer = torch.einsum('i,j->ij', vector.float(), vector.float())   # Outer Product using einsum
einsum_trace = torch.einsum('ii->', matrix.float())   # Trace of a Matrix using einsum

print("\nEinsum Matrix Multiplication:\n", einsum_matmul)
print("Einsum Outer Product:\n", einsum_outer)
print("Einsum Trace:", einsum_trace.item())


Einsum Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])
Einsum Outer Product:
 tensor([[1., 2., 3.],
        [2., 4., 6.],
        [3., 6., 9.]])
Einsum Trace: 5.0


In [ ]:
# Special Tensors in PyTorch
zeros_tensor = torch.zeros((2, 3))
ones_tensor = torch.ones((2, 3))
identity_matrix = torch.eye(3)

print("\nZeros Tensor:\n", zeros_tensor)
print("Ones Tensor:\n", ones_tensor)
print("Identity Matrix:\n", identity_matrix)


Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Identity Matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# Less Commonly Used Operations in PyTorch
expanded_tensor = vector.expand(4, -1)   # Expanding dimensions without copying data
permuted_tensor = tensor_3d.permute(2, 1, 0)   # Permuting dimensions of a tensor

print("\nExpanded Tensor:\n", expanded_tensor)
print("Permuted Tensor Shape:", permuted_tensor.shape)


Expanded Tensor:
 tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
Permuted Tensor Shape: torch.Size([3, 3, 3])
