In [1]:
# %% [markdown]
# # Exploring Tensor Operations in PyTorch
#
# This notebook covers several basic and some less common tensor operations in PyTorch.
# We include:
# - Tensor creation, reshaping, and transposition.
# - Elementwise and matrix multiplication operations.
# - Demonstrations of `torch.einsum` for flexible tensor operations.
# - Additional operations such as concatenation, stacking, and use of the einops library.
#
# For additional reference:
# - [PyTorch Tensors - Deep Learning with PyTorch](https://github.com/deep-learning-with-pytorch/dlwpt-code/blob/master/p1ch3/1_tensors.ipynb) :contentReference[oaicite:2]{index=2}
# - [PyTorch Tensor Operations Presentation](https://docs.google.com/presentation/d/13Oo5gXwcsoq9oMC4XriAyxkvgicatBxfI4cZzDhRyiE/edit#slide=id.p) :contentReference[oaicite:3]{index=3}

# %% [code]
import torch
import numpy as np

# Create basic tensors
x = torch.tensor([1, 2, 3])
y = torch.tensor([[1, 2, 3], [4, 5, 6]])

print("Tensor x:", x)
print("Tensor y:\n", y)

# %% [markdown]
# ## Reshaping and Transposing
#
# PyTorch makes it easy to reshape and transpose tensors.
#

# %% [code]
# Reshape tensor y from (2,3) to (3,2)
z = y.view(3, 2)
print("Reshaped tensor z (3,2):\n", z)

# Transpose of z (for 2D, .t() is available)
print("Transpose of z:\n", z.t())

# %% [markdown]
# ## Elementwise Operations and Matrix Multiplication
#

# %% [code]
# Elementwise square of tensor x
square_x = x * x
print("Element-wise square of x:", square_x)

# Matrix multiplication example
m1 = torch.tensor([[1, 2], [3, 4]])
m2 = torch.tensor([[2, 0], [1, 2]])
matmul_result = torch.mm(m1, m2)
print("Matrix multiplication result:\n", matmul_result)

# %% [markdown]
# ## Demonstrating Einstein Summation (einsum)
#
# Using `torch.einsum` we perform:
#
# 1. **Sum of elementwise product:** Computes the sum of products over all corresponding elements.
# 2. **Matrix multiplication using einsum.**
#

# %% [code]
# Example 1: Sum over elementwise product of two matrices
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
einsum_result = torch.einsum('ij,ij->', A, B)
print("Einsum (elementwise product sum) result:", einsum_result.item())

# Example 2: Matrix multiplication using einsum
einsum_matmul = torch.einsum('ik,kj->ij', m1, m2)
print("Matrix multiplication using einsum:\n", einsum_matmul)

# %% [markdown]
# ## Additional Tensor Operations
#
# Here we explore some additional operations:
#
# - **Broadcasting addition:** Automatically expands dimensions.
# - **Concatenation and stacking:** Combine tensors along various dimensions.
# - **Using einops:** For intuitive tensor dimension reordering.
#

# %% [code]
# Broadcasting addition example
tensor1 = torch.tensor([[1, 2, 3]])
tensor2 = torch.tensor([[10], [20], [30]])
broadcast_add = tensor1 + tensor2  # This will broadcast to shape (3,3)
print("Broadcast addition result:\n", broadcast_add)

# Concatenation and stacking examples
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])
concatenated = torch.cat((tensor_a, tensor_b), dim=0)
stacked = torch.stack((tensor_a, tensor_b), dim=0)
print("Concatenated tensor:", concatenated)
print("Stacked tensor:\n", stacked)

# %% [code]
# Optional: Using einops for more expressive tensor operations
try:
    from einops import rearrange
    # Create a random tensor with shape (batch, seq, features)
    tensor = torch.randn(2, 3, 4)
    # Rearrange to combine batch and sequence dimensions
    rearranged = rearrange(tensor, 'b n d -> (b n) d')
    print("Original tensor shape:", tensor.shape)
    print("Rearranged tensor shape using einops:", rearranged.shape)
except ImportError:
    print("einops not installed. You can install it via `pip install einops`.")


Tensor x: tensor([1, 2, 3])
Tensor y:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped tensor z (3,2):
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
Transpose of z:
 tensor([[1, 3, 5],
        [2, 4, 6]])
Element-wise square of x: tensor([1, 4, 9])
Matrix multiplication result:
 tensor([[ 4,  4],
        [10,  8]])
Einsum (elementwise product sum) result: 70.0
Matrix multiplication using einsum:
 tensor([[ 4,  4],
        [10,  8]])
Broadcast addition result:
 tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
Concatenated tensor: tensor([1, 2, 3, 4, 5, 6])
Stacked tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Original tensor shape: torch.Size([2, 3, 4])
Rearranged tensor shape using einops: torch.Size([6, 4])
