In [1]:
# %% [markdown]
# # Exploring Tensor Operations in TensorFlow 2.0
#
# In this notebook we explore several basic tensor operations in TensorFlow 2.0.
# We cover creation, reshaping, transposition, elementwise operations, matrix multiplication,
# and demonstrate the powerful `einsum` function.
#
# For further reading:
# - [TensorFlow Guide: Tensors](https://www.tensorflow.org/guide/tensor) :contentReference[oaicite:0]{index=0}
# - [Sample Colab Notebook](https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/guide/tensor.ipynb) :contentReference[oaicite:1]{index=1}

# %% [code]
import tensorflow as tf
import numpy as np

# Create basic tensors
a = tf.constant([1, 2, 3])
b = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Tensor a:", a.numpy())
print("Tensor b:", b.numpy())

# %% [markdown]
# ## Reshaping and Transposing
#
# We can reshape and transpose tensors easily.
#

# %% [code]
# Reshape tensor b from (2,3) to (3,2)
c = tf.reshape(b, (3, 2))
print("Reshaped tensor c (3,2):\n", c.numpy())

# Transpose of c
c_transposed = tf.transpose(c)
print("Transpose of c:\n", c_transposed.numpy())

# %% [markdown]
# ## Elementwise Operations and Matrix Multiplication
#
# Here we perform elementwise multiplication and also standard matrix multiplication.
#

# %% [code]
# Elementwise square of tensor a
d = a * a
print("Element-wise square of a:", d.numpy())

# Matrix multiplication example
m1 = tf.constant([[1, 2], [3, 4]])
m2 = tf.constant([[2, 0], [1, 2]])
matmul_result = tf.matmul(m1, m2)
print("Matrix multiplication result:\n", matmul_result.numpy())

# %% [markdown]
# ## Demonstrating Einstein Summation (einsum)
#
# The `tf.einsum` function allows for flexible, readable tensor operations. Here are two examples:
#
# 1. **Sum of element-wise products:** Computes the sum over all products of corresponding elements.
# 2. **Matrix multiplication using einsum:** An alternative way to perform standard matrix multiplication.
#

# %% [code]
# Example 1: Sum over elementwise multiplication of two matrices
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
einsum_result = tf.einsum('ij,ij->', A, B)
print("Einsum (elementwise product sum) result:", einsum_result.numpy())

# Example 2: Matrix multiplication using einsum
einsum_matmul = tf.einsum('ik,kj->ij', m1, m2)
print("Matrix multiplication using einsum:\n", einsum_matmul.numpy())

# %% [markdown]
# ## Additional Tensor Operations
#
# - **Broadcasting:** Automatically expands smaller tensors during arithmetic.
# - **Gathering elements:** Extract specific elements based on indices.
#

# %% [code]
# Broadcasting addition example
tensor1 = tf.constant([[1, 2, 3]])
tensor2 = tf.constant([[10], [20], [30]])
broadcast_add = tensor1 + tensor2  # Broadcasts to (3,3)
print("Broadcast addition result:\n", broadcast_add.numpy())

# Gathering elements from tensor 'a'
indices = tf.constant([0, 2])
gather_result = tf.gather(a, indices)
print("Gather result:", gather_result.numpy())


Tensor a: [1 2 3]
Tensor b: [[1 2 3]
 [4 5 6]]
Reshaped tensor c (3,2):
 [[1 2]
 [3 4]
 [5 6]]
Transpose of c:
 [[1 3 5]
 [2 4 6]]
Element-wise square of a: [1 4 9]
Matrix multiplication result:
 [[ 4  4]
 [10  8]]
Einsum (elementwise product sum) result: 70.0
Matrix multiplication using einsum:
 [[ 4  4]
 [10  8]]
Broadcast addition result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Gather result: [1 3]
