In [ ]:
# TensorFlow 2.0 Tensor Operations Colab Notebook
import tensorflow as tf
import numpy as np

In [ ]:
# Basic Tensor Creation
scalar = tf.constant(5)  # Scalar (Rank-0 Tensor)
vector = tf.constant([1, 2, 3])  # Vector (Rank-1 Tensor)
matrix = tf.constant([[1, 2], [3, 4]])  # Matrix (Rank-2 Tensor)
tensor_3d = tf.random.uniform((3, 3, 3))  # Rank-3 Tensor with random values

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("3D Tensor:\n", tensor_3d)

Scalar: tf.Tensor(5, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3D Tensor:
 tf.Tensor(
[[[0.6104157  0.11798787 0.7405679 ]
  [0.92130387 0.43568456 0.42289114]
  [0.36583805 0.6479802  0.7970102 ]]

 [[0.42761183 0.8731713  0.19582093]
  [0.94245195 0.13331056 0.48578215]
  [0.39179862 0.6129129  0.51321876]]

 [[0.13179123 0.7748139  0.1283232 ]
  [0.20895112 0.72030795 0.5131079 ]
  [0.70523787 0.5871533  0.6723876 ]]], shape=(3, 3, 3), dtype=float32)


In [ ]:
# Basic Arithmetic Operations
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
add_result = tf.add(a, b)
mul_result = tf.multiply(a, b)
matmul_result = tf.matmul(a, b)

print("\nAddition:\n", add_result)
print("Element-wise Multiplication:\n", mul_result)
print("Matrix Multiplication:\n", matmul_result)


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
# Advanced Operations
reshaped_tensor = tf.reshape(a, [4])  # Reshaping
transposed_tensor = tf.transpose(a)  # Transposition
reduced_sum = tf.reduce_sum(a)  # Summing all elements
broadcasted_tensor = a + tf.constant([1, 2])  # Broadcasting

print("\nReshaped Tensor:", reshaped_tensor)
print("Transposed Tensor:\n", transposed_tensor)
print("Reduced Sum:", reduced_sum)
print("Broadcasted Tensor:\n", broadcasted_tensor)


Reshaped Tensor: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Transposed Tensor:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
Reduced Sum: tf.Tensor(10, shape=(), dtype=int32)
Broadcasted Tensor:
 tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32)


In [ ]:
# Einsum Demonstrations
# Matrix Multiplication using einsum
einsum_matmul = tf.einsum('ij,jk->ik', a, b)

# Outer Product using einsum
einsum_outer = tf.einsum('i,j->ij', vector, vector)

# Trace of a Matrix using einsum
einsum_trace = tf.einsum('ii', matrix)

print("\nEinsum Matrix Multiplication:\n", einsum_matmul)
print("Einsum Outer Product:\n", einsum_outer)
print("Einsum Trace:", einsum_trace)


Einsum Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Einsum Outer Product:
 tf.Tensor(
[[1 2 3]
 [2 4 6]
 [3 6 9]], shape=(3, 3), dtype=int32)
Einsum Trace: tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
# Special Tensors
zeros_tensor = tf.zeros((2, 3))
ones_tensor = tf.ones((2, 3))
identity_matrix = tf.eye(3)

print("\nZeros Tensor:\n", zeros_tensor)
print("Ones Tensor:\n", ones_tensor)
print("Identity Matrix:\n", identity_matrix)


Zeros Tensor:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
Ones Tensor:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Identity Matrix:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
